'use strict';

function plural(count, singular, pluralWord) {
  return count === 1 ? singular : (pluralWord || singular + 's');
}

function escapeMarkdownText(value) {
  const placeholder = 'LANREDACTEDPLACEHOLDER7D9A';
  return String(value)
    .replace(/\[REDACTED\]/g, placeholder)
    .replace(/[\r\n\t\0]/g, ' ')
    .replace(/\\/g, '\\\\')
    .replace(/([\`*_{}\[\]()#+.!<>|~-])/g, '\\$1')
    .replace(new RegExp(placeholder, 'g'), '[REDACTED]');
}

function renderList(items, renderItem) {
  if (!items || items.length === 0) return '- None\n';
  return items.map((item) => '- ' + (renderItem ? renderItem(item) : escapeMarkdownText(item))).join('\n') + '\n';
}

function renderMarkdownSummary(check) {
  const lines = [];
  lines.push('# Living Architecture Nodes Diagnostic Summary');
  lines.push('');
  lines.push('Generated: ' + escapeMarkdownText(check.timestamp));
  lines.push('');
  lines.push('## Basic CI status');
  lines.push('');
  lines.push('- Status: **' + escapeMarkdownText(check.status.toUpperCase()) + '**');
  lines.push('- Maintenance score: **' + check.healthScore + '/100** (heuristic, not a semantic architecture verdict)');
  lines.push('- Verification scope: **' + escapeMarkdownText(check.verification.scope) + '**');
  lines.push('- Semantic architecture: **' + escapeMarkdownText(check.verification.semanticArchitecture.status) + '**');
  lines.push('- Source files scanned: ' + check.sourceFileCount);
  lines.push('- Node files found: ' + check.nodeFileCount);
  lines.push('- Missing required artifacts: ' + check.missingRequired.length);
  lines.push('- Missing nodes: ' + check.missingNodes.length);
  lines.push('- Dirty nodes: ' + check.dirtyNodes.length);
  lines.push('- Orphan nodes: ' + check.orphanNodes.length);
  lines.push('');

  lines.push('## Missing required artifacts');
  lines.push('');
  lines.push(renderList(check.missingRequired));

  lines.push('## Missing node files');
  lines.push('');
  lines.push(renderList(check.missingNodes, (item) =>
    escapeMarkdownText(item.sourcePath) + ' needs ' + escapeMarkdownText(item.nodePath)
  ));

  lines.push('## Dirty node risks');
  lines.push('');
  lines.push(renderList(check.dirtyNodes, (item) =>
    escapeMarkdownText(item.sourcePath) + ' changed without matching node update ' + escapeMarkdownText(item.nodePath)
  ));

  lines.push('## Orphan node files');
  lines.push('');
  lines.push(renderList(check.orphanNodes));

  lines.push('## Suggested investigation order');
  lines.push('');
  if (check.missingRequired.length > 0) {
    lines.push('- Add missing required ' + plural(check.missingRequired.length, 'artifact') + ': ' + check.missingRequired.map(escapeMarkdownText).join(', ') + '.');
  } else if (check.missingNodes.length > 0) {
    lines.push('- Add missing .node.md companion files for source modules.');
  } else if (check.dirtyNodes.length > 0) {
    lines.push('- Review changed source files and update the matching .node.md diagnostic/dynamic layers.');
  } else {
    lines.push('- No immediate architecture-memory blockers detected.');
  }

  lines.push('- Review ARCH.md for intent vs reality gaps.');
  lines.push('- Review NERVE.md for cascade risks and recurring bug patterns.');
  lines.push('- Update CHANGELOG.node.md after cross-cutting changes.');
  lines.push('');
  lines.push('> NOT_VERIFIED means that semantic architecture verification was not executed. It does not mean failed or unsafe.');
  lines.push('');
  lines.push('Privacy: source contents, absolute runner/workspace paths, and full repository inventories are not included in this handoff.');
  lines.push('');
  lines.push('---');
  lines.push('Generated by Living Architecture Nodes Action.');
  lines.push('');
  return lines.join('\n');
}

function renderConsoleSummary(check) {
  return [
    'Living Architecture Nodes: ' + check.status.toUpperCase() + ' (' + check.healthScore + '/100 basic maintenance score)',
    'Verification scope: ' + check.verification.scope,
    'Semantic architecture: ' + check.verification.semanticArchitecture.status,
    'Sources: ' + check.sourceFileCount,
    'Nodes: ' + check.nodeFileCount,
    'Missing required: ' + check.missingRequired.length,
    'Missing nodes: ' + check.missingNodes.length,
    'Dirty nodes: ' + check.dirtyNodes.length,
    'Orphan nodes: ' + check.orphanNodes.length
  ].join('\n');
}

module.exports = { renderMarkdownSummary, renderConsoleSummary, escapeMarkdownText };
